version: '3.7'
networks:
  sparkrentals:

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
      - ./v1/db/mongod.conf:/etc/mongod.conf
    container_name: "mongodb"
    ports:
      - 27017:27017
    networks:
      sparkrentals:
    entrypoint: ["mongod","--config","/etc/mongod.conf"]

  dataGenerator:
    image: spark-rentals-data-generator:1.0
    entrypoint: ["node", "/etc/autoGen.js"]
    depends_on:
    - mongodb_container

  server:
    image: spark-rentals-api:1.0
    build: .
    ports:
      - "8393:8393"
    container_name: "api-server"
    env_file:
      - "./.env"
    volumes:
    - ./:/usr/src/app
    restart: "always"
    depends_on:
    - mongodb_container
    networks:
      sparkrentals:


volumes:
  mongodb_data_container: