version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./v1/db/mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod","--config","/etc/mongod.conf"]

  api:
    image: express-rest-api
    build: .
    ports:
      - "8393:8393"
    volumes:
    - ./:/usr/src/app


volumes:
  mongodb_data_container: